version: "3.6"
services:
  frontend:
    image: harbor.psgtecnologiaaplicada.com.br/academia/chat-cripto-front:${VERSION_IMG}
    environment:
      REACT_APP_SOCKET: ${REACT_APP_SOCKET}
      REACT_APP_API: ${REACT_APP_API}
    networks:
      - traefik-public
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.chat-cripto-front-academia.rule=Host(`chat-cripto.psg.org`)"
        - "traefik.http.routers.chat-cripto-front-academia.service=chat-cripto-front-academia"
        - "traefik.http.routers.chat-cripto-front-academia.entrypoints=web"
        - "traefik.http.services.chat-cripto-front-academia.loadbalancer.server.port=80"
networks:
  traefik-public:
    external: true
